#!/bin/sh
MEMBERS=$(serf members |wc |awk '{ print $1; }')
MIN_MEMBERS=${MIN_MEMBERS:-3}

while [ "$MIN_MEMBERS" -gt "$MEMBERS" ] 
do
	sleep 5
	MEMBERS=$(serf members |wc |awk '{ print $1; }')
done

NETWORK=${NETWORK:-10.0.1.*}
export IP=$(hostname -i | grep -o $NETWORK )
export LEADER=$(serf members|sort -k 2 | head -n 1 | cut -f 3 -d ' ' |cut -f 1 -d ':')
#if [$IP==$LEADER] 
#then
	exec /usr/local/bin/consul agent -server -bind 0.0.0.0 -client 0.0.0.0 -advertise $IP -bootstrap-expect $MIN_MEMBERS -join $LEADER -retry-join $LEADER -data-dir=/tmp  >>/var/log/consul.log 2>&1
#else
#	exec /usr/local/bin/consul agent -server -bind 0.0.0.0 -client 0.0.0.0 -advertise $IP -data-dir=/tmp -join $LEADER -retry-join $LEADER  >>/var/log/consul.log 2>&1
#fi
